test: "/QA_data/SemEval_data/TEST_INPUT/SemEval2016_task3_test_input/English/2017"
dev: "/QA_data/SemEval_data/semeval2016-task3-cqa-ql-traindev-v3.2 ENG/v3.2/dev"
train: "/QA_data/SemEval_data/semeval2016-task3-cqa-ql-traindev-v3.2 ENG/v3.2/train"



